// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";
import { RequestStatus } from "./request_status_type";
// Mark import as potentially unused
declare type __keep_RequestStatus = RequestStatus;


export type ExchangeRequest = {
  requestId: bigint,
  userIdentity: __Identity,
  userWalletAddress: string,
  phoneNumber: string,
  fullName: string,
  usdcAmount: number,
  kwachaAmount: number,
  status: RequestStatus,
  createdAt: __Timestamp,
  notes: string,
};
/**
 * An object for generated helper functions.
 */
export const ExchangeRequest = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Product({
      elements: [
        { name: "requestId", algebraicType: __AlgebraicTypeValue.U64},
        { name: "userIdentity", algebraicType: __AlgebraicTypeValue.createIdentityType()},
        { name: "userWalletAddress", algebraicType: __AlgebraicTypeValue.String},
        { name: "phoneNumber", algebraicType: __AlgebraicTypeValue.String},
        { name: "fullName", algebraicType: __AlgebraicTypeValue.String},
        { name: "usdcAmount", algebraicType: __AlgebraicTypeValue.F64},
        { name: "kwachaAmount", algebraicType: __AlgebraicTypeValue.F64},
        { name: "status", algebraicType: RequestStatus.getTypeScriptAlgebraicType()},
        { name: "createdAt", algebraicType: __AlgebraicTypeValue.createTimestampType()},
        { name: "notes", algebraicType: __AlgebraicTypeValue.String},
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: ExchangeRequest): void {
    __AlgebraicTypeValue.serializeValue(writer, ExchangeRequest.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): ExchangeRequest {
    return __AlgebraicTypeValue.deserializeValue(reader, ExchangeRequest.getTypeScriptAlgebraicType());
  },

}

export default ExchangeRequest;


