// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.5.0 (commit ).

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";

// Import and reexport all reducer arg types
import { AddAdmin } from "./add_admin_reducer.ts";
export { AddAdmin };
import { CreateExchangeRequest } from "./create_exchange_request_reducer.ts";
export { CreateExchangeRequest };
import { GetAllRequestsForAdmin } from "./get_all_requests_for_admin_reducer.ts";
export { GetAllRequestsForAdmin };
import { MarkRequestCompletedByUser } from "./mark_request_completed_by_user_reducer.ts";
export { MarkRequestCompletedByUser };
import { UpdateRequestStatusAdmin } from "./update_request_status_admin_reducer.ts";
export { UpdateRequestStatusAdmin };

// Import and reexport all table handle types
import { AdminTableHandle } from "./admin_table.ts";
export { AdminTableHandle };
import { ExchangeRequestTableHandle } from "./exchange_request_table.ts";
export { ExchangeRequestTableHandle };

// Import and reexport all types
import { Admin } from "./admin_type.ts";
export { Admin };
import { ExchangeRequest } from "./exchange_request_type.ts";
export { ExchangeRequest };
import { RequestStatus } from "./request_status_type.ts";
export { RequestStatus };

const REMOTE_MODULE = {
  tables: {
    admin: {
      tableName: "admin",
      rowType: Admin.getTypeScriptAlgebraicType(),
      primaryKey: "identity",
      primaryKeyInfo: {
        colName: "identity",
        colType: (Admin.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    exchange_request: {
      tableName: "exchange_request",
      rowType: ExchangeRequest.getTypeScriptAlgebraicType(),
      primaryKey: "requestId",
      primaryKeyInfo: {
        colName: "requestId",
        colType: (ExchangeRequest.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
  },
  reducers: {
    add_admin: {
      reducerName: "add_admin",
      argsType: AddAdmin.getTypeScriptAlgebraicType(),
    },
    create_exchange_request: {
      reducerName: "create_exchange_request",
      argsType: CreateExchangeRequest.getTypeScriptAlgebraicType(),
    },
    get_all_requests_for_admin: {
      reducerName: "get_all_requests_for_admin",
      argsType: GetAllRequestsForAdmin.getTypeScriptAlgebraicType(),
    },
    mark_request_completed_by_user: {
      reducerName: "mark_request_completed_by_user",
      argsType: MarkRequestCompletedByUser.getTypeScriptAlgebraicType(),
    },
    update_request_status_admin: {
      reducerName: "update_request_status_admin",
      argsType: UpdateRequestStatusAdmin.getTypeScriptAlgebraicType(),
    },
  },
  versionInfo: {
    cliVersion: "1.5.0",
  },
  // Constructors which are used by the DbConnectionImpl to
  // extract type information from the generated RemoteModule.
  //
  // NOTE: This is not strictly necessary for `eventContextConstructor` because
  // all we do is build a TypeScript object which we could have done inside the
  // SDK, but if in the future we wanted to create a class this would be
  // necessary because classes have methods, so we'll keep it.
  eventContextConstructor: (imp: __DbConnectionImpl, event: __Event<Reducer>) => {
    return {
      ...(imp as DbConnection),
      event
    }
  },
  dbViewConstructor: (imp: __DbConnectionImpl) => {
    return new RemoteTables(imp);
  },
  reducersConstructor: (imp: __DbConnectionImpl, setReducerFlags: SetReducerFlags) => {
    return new RemoteReducers(imp, setReducerFlags);
  },
  setReducerFlagsConstructor: () => {
    return new SetReducerFlags();
  }
}

// A type representing all the possible variants of a reducer.
export type Reducer = never
| { name: "AddAdmin", args: AddAdmin }
| { name: "CreateExchangeRequest", args: CreateExchangeRequest }
| { name: "GetAllRequestsForAdmin", args: GetAllRequestsForAdmin }
| { name: "MarkRequestCompletedByUser", args: MarkRequestCompletedByUser }
| { name: "UpdateRequestStatusAdmin", args: UpdateRequestStatusAdmin }
;

export class RemoteReducers {
  constructor(private connection: __DbConnectionImpl, private setCallReducerFlags: SetReducerFlags) {}

  addAdmin(identity: __Identity) {
    const __args = { identity };
    let __writer = new __BinaryWriter(1024);
    AddAdmin.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("add_admin", __argsBuffer, this.setCallReducerFlags.addAdminFlags);
  }

  onAddAdmin(callback: (ctx: ReducerEventContext, identity: __Identity) => void) {
    this.connection.onReducer("add_admin", callback);
  }

  removeOnAddAdmin(callback: (ctx: ReducerEventContext, identity: __Identity) => void) {
    this.connection.offReducer("add_admin", callback);
  }

  createExchangeRequest(userWalletAddress: string, phoneNumber: string, fullName: string, usdcAmount: number, notes: string) {
    const __args = { userWalletAddress, phoneNumber, fullName, usdcAmount, notes };
    let __writer = new __BinaryWriter(1024);
    CreateExchangeRequest.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("create_exchange_request", __argsBuffer, this.setCallReducerFlags.createExchangeRequestFlags);
  }

  onCreateExchangeRequest(callback: (ctx: ReducerEventContext, userWalletAddress: string, phoneNumber: string, fullName: string, usdcAmount: number, notes: string) => void) {
    this.connection.onReducer("create_exchange_request", callback);
  }

  removeOnCreateExchangeRequest(callback: (ctx: ReducerEventContext, userWalletAddress: string, phoneNumber: string, fullName: string, usdcAmount: number, notes: string) => void) {
    this.connection.offReducer("create_exchange_request", callback);
  }

  getAllRequestsForAdmin() {
    this.connection.callReducer("get_all_requests_for_admin", new Uint8Array(0), this.setCallReducerFlags.getAllRequestsForAdminFlags);
  }

  onGetAllRequestsForAdmin(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("get_all_requests_for_admin", callback);
  }

  removeOnGetAllRequestsForAdmin(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("get_all_requests_for_admin", callback);
  }

  markRequestCompletedByUser(requestId: bigint, notes: string) {
    const __args = { requestId, notes };
    let __writer = new __BinaryWriter(1024);
    MarkRequestCompletedByUser.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("mark_request_completed_by_user", __argsBuffer, this.setCallReducerFlags.markRequestCompletedByUserFlags);
  }

  onMarkRequestCompletedByUser(callback: (ctx: ReducerEventContext, requestId: bigint, notes: string) => void) {
    this.connection.onReducer("mark_request_completed_by_user", callback);
  }

  removeOnMarkRequestCompletedByUser(callback: (ctx: ReducerEventContext, requestId: bigint, notes: string) => void) {
    this.connection.offReducer("mark_request_completed_by_user", callback);
  }

  updateRequestStatusAdmin(requestId: bigint, newStatus: RequestStatus, notes: string) {
    const __args = { requestId, newStatus, notes };
    let __writer = new __BinaryWriter(1024);
    UpdateRequestStatusAdmin.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("update_request_status_admin", __argsBuffer, this.setCallReducerFlags.updateRequestStatusAdminFlags);
  }

  onUpdateRequestStatusAdmin(callback: (ctx: ReducerEventContext, requestId: bigint, newStatus: RequestStatus, notes: string) => void) {
    this.connection.onReducer("update_request_status_admin", callback);
  }

  removeOnUpdateRequestStatusAdmin(callback: (ctx: ReducerEventContext, requestId: bigint, newStatus: RequestStatus, notes: string) => void) {
    this.connection.offReducer("update_request_status_admin", callback);
  }

}

export class SetReducerFlags {
  addAdminFlags: __CallReducerFlags = 'FullUpdate';
  addAdmin(flags: __CallReducerFlags) {
    this.addAdminFlags = flags;
  }

  createExchangeRequestFlags: __CallReducerFlags = 'FullUpdate';
  createExchangeRequest(flags: __CallReducerFlags) {
    this.createExchangeRequestFlags = flags;
  }

  getAllRequestsForAdminFlags: __CallReducerFlags = 'FullUpdate';
  getAllRequestsForAdmin(flags: __CallReducerFlags) {
    this.getAllRequestsForAdminFlags = flags;
  }

  markRequestCompletedByUserFlags: __CallReducerFlags = 'FullUpdate';
  markRequestCompletedByUser(flags: __CallReducerFlags) {
    this.markRequestCompletedByUserFlags = flags;
  }

  updateRequestStatusAdminFlags: __CallReducerFlags = 'FullUpdate';
  updateRequestStatusAdmin(flags: __CallReducerFlags) {
    this.updateRequestStatusAdminFlags = flags;
  }

}

export class RemoteTables {
  constructor(private connection: __DbConnectionImpl) {}

  get admin(): AdminTableHandle {
    // clientCache is a private property
    return new AdminTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<Admin>(REMOTE_MODULE.tables.admin));
  }

  get exchangeRequest(): ExchangeRequestTableHandle {
    // clientCache is a private property
    return new ExchangeRequestTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<ExchangeRequest>(REMOTE_MODULE.tables.exchange_request));
  }
}

export class SubscriptionBuilder extends __SubscriptionBuilderImpl<RemoteTables, RemoteReducers, SetReducerFlags> { }

export class DbConnection extends __DbConnectionImpl<RemoteTables, RemoteReducers, SetReducerFlags> {
  static builder = (): __DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext> => {
    return new __DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext>(REMOTE_MODULE, (imp: __DbConnectionImpl) => imp as DbConnection);
  }
  subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  }
}

export type EventContext = __EventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type ReducerEventContext = __ReducerEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type SubscriptionEventContext = __SubscriptionEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
export type ErrorContext = __ErrorContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
